services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dronetech
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    ports:
      - "5432:7777"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dronetech
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: